# Generated by Django 3.2.12 on 2022-02-18 04:36

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_alter_city_options'),
        ('cars', '0004_auto_20220218_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('rent_payment_currency', djmoney.models.fields.CurrencyField(choices=[('TRY', 'TRY ₺')], default='XYZ', editable=False, max_length=3)),
                ('rent_payment', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=6, verbose_name='Rent payment')),
                ('deposit_currency', djmoney.models.fields.CurrencyField(choices=[('TRY', 'TRY ₺')], default='XYZ', editable=False, max_length=3)),
                ('deposit', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8, verbose_name='Deposit')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='cars.car', verbose_name='Car')),
                ('drop_off', models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents_pick_up', to='locations.location', verbose_name='Pick up'), on_delete=django.db.models.deletion.CASCADE, related_name='rents_drop_off', to='locations.location', verbose_name='Drop off')),
                ('pick_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents_pick_up', to='locations.location', verbose_name='Pick up')),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
                'ordering': ('-created',),
            },
        ),
    ]
