# Generated by Django 3.2.12 on 2022-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_alter_rent_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=None, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateTimeField(default=None, verbose_name='Start date'),
        ),
    ]
