# Generated by Django 3.2.12 on 2022-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_options'),
        ('rents', '0004_auto_20220218_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='drop_off',
        ),
        migrations.AddField(
            model_name='rent',
            name='drop_off',
            field=models.ManyToManyField(default=models.ManyToManyField(related_name='rents_pick_up', to='locations.Location', verbose_name='Pick up'), related_name='rents_drop_off', to='locations.Location', verbose_name='Drop off'),
        ),
        migrations.RemoveField(
            model_name='rent',
            name='pick_up',
        ),
        migrations.AddField(
            model_name='rent',
            name='pick_up',
            field=models.ManyToManyField(related_name='rents_pick_up', to='locations.Location', verbose_name='Pick up'),
        ),
    ]
