# Generated by Django 3.2.12 on 2022-02-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_options'),
        ('rents', '0005_auto_20220218_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='drop_off',
            field=models.ManyToManyField(related_name='rents_drop_off', to='locations.Location', verbose_name='Drop off'),
        ),
    ]
