# Generated by Django 3.2.12 on 2022-02-28 03:54

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0006_alter_rent_drop_off'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='rent_payment_currency',
            new_name='price_currency',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rent_payment',
        ),
        migrations.AddField(
            model_name='rent',
            name='condition',
            field=models.TextField(default=1, verbose_name='Condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='delivery_type',
            field=models.CharField(choices=[('In-terminal Office', 'In-terminal Office'), ('Office', 'Office'), ('Valet Service', 'Valet Service'), ('Out of Terminal Valet Service', 'Out of Terminal Valet Service')], default=1, max_length=63, verbose_name='Delivery type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='deposit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Deposit'),
        ),
    ]
