# Generated by Django 3.2.12 on 2022-02-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20220228_1133'),
        ('rents', '0009_auto_20220228_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='driver_conditions',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='driver_requirements',
        ),
        migrations.AddField(
            model_name='rent',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='companies.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
