# Generated by Django 3.2.12 on 2022-02-17 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model name')),
                ('model_year', models.CharField(max_length=4, verbose_name='Model year')),
                ('engine_capacity', models.CharField(choices=[('L_1', '< 1000'), ('L_2', '1001 - 1300'), ('L_3', '1301 - 1400'), ('L_4', '1401 - 1600'), ('L_5', '1601 - 1800'), ('M_1', '1801 - 2000'), ('M_2', '2001 - 2500'), ('M_3', '2501 - 3000'), ('H_1', '3001 - 3500'), ('H_2', '3501 - 4000'), ('H_3', '4001 - 10000'), ('E', 'Electricity')], max_length=3)),
                ('car_type', models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('7', '7'), ('10', '10')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.brand', verbose_name='Car brand')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.class', verbose_name='Car class')),
                ('car_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.transmisson', verbose_name='Car transmission')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car/images/', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='cars.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Transmisson',
                'verbose_name_plural': 'Transmissons',
                'ordering': ('-created',),
            },
        ),
    ]
