# Generated by Django 3.2.12 on 2022-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_main_image',
            field=models.ImageField(default=1, upload_to='car/images/main', verbose_name='Car main image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='car/images/others', verbose_name='Image'),
        ),
    ]
