# Generated by Django 3.2.12 on 2022-02-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20220218_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('D', 'Diesel'), ('P', 'Petrol'), ('E', 'Electricity'), ('H', 'Hybrid'), ('G', 'Gaz')], default=1, max_length=1, verbose_name='Fuel type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('SDN', 'Sedan'), ('CPE', 'Coupe'), ('SCR', 'Sports car'), ('WGN', 'Wagon'), ('HTB', 'Hatchback'), ('CNV', 'Convertible'), ('SUV', 'SUV'), ('MNV', 'Minivan'), ('PCK', 'Pickup')], max_length=3, verbose_name='Car type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(choices=[('L_1', '< 1000'), ('L_2', '1001 - 1300'), ('L_3', '1301 - 1400'), ('L_4', '1401 - 1600'), ('L_5', '1601 - 1800'), ('M_1', '1801 - 2000'), ('M_2', '2001 - 2500'), ('M_3', '2501 - 3000'), ('H_1', '3001 - 3500'), ('H_2', '3501 - 4000'), ('H_3', '4001 - 10000'), ('E', 'Electricity')], max_length=3, verbose_name='Engine capacity'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seat_number',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('7', '7'), ('10', '10')], max_length=2, verbose_name='Seat number'),
        ),
    ]
