# Generated by Django 3.2.12 on 2022-02-28 04:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Title')),
                ('rental_conditions', models.TextField(verbose_name='Rental conditions')),
                ('address', models.CharField(max_length=127, verbose_name='Address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DriverRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('min_driver_age', models.PositiveSmallIntegerField(verbose_name='Min driver age')),
                ('min_years_of_license', models.PositiveSmallIntegerField(verbose_name='Min years of license')),
                ('min_young_driver_age', models.PositiveSmallIntegerField(verbose_name='Min young driver age')),
                ('min_years_of_youth_drivers_license', models.PositiveSmallIntegerField(verbose_name='Min years of youth drivers license')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requirements', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Driver requirement',
                'verbose_name_plural': 'Driver requirements',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DriverCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('deposit_fee_currency', djmoney.models.fields.CurrencyField(choices=[('TRY', 'TRY ₺')], default='XYZ', editable=False, max_length=3)),
                ('deposit_fee', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Deposit fee')),
                ('kilometer_limit', models.PositiveIntegerField(verbose_name='Kilometer limit')),
                ('valet_fee_currency', djmoney.models.fields.CurrencyField(choices=[('TRY', 'TRY ₺')], default='XYZ', editable=False, max_length=3)),
                ('valet_fee', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valet fee')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_conditions', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Driver condition',
                'verbose_name_plural': 'Driver conditions',
                'ordering': ('-created',),
            },
        ),
    ]
