# Generated by Django 3.2.12 on 2022-02-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Discount percentage'),
            preserve_default=False,
        ),
    ]
