# Generated by Django 3.2.12 on 2022-02-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivercondition',
            name='company',
        ),
        migrations.RemoveField(
            model_name='driverrequirement',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='driver_conditions',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.drivercondition', verbose_name='Driver conditions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='driver_requirements',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.driverrequirement', verbose_name='Driver requirements'),
            preserve_default=False,
        ),
    ]
