# Generated by Django 3.2.12 on 2022-02-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-created',), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
